# Generated by Django 4.0.6 on 2022-08-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionarios'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientes',
            new_name='Cliente',
        ),
        migrations.RenameModel(
            old_name='Funcionarios',
            new_name='Funcionario',
        ),
    ]
