# Generated by Django 4.0.6 on 2022-08-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_clientes_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='dia',
            field=models.DateTimeField(blank=True, max_length=100, null=True, verbose_name='Dia e Horario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='funcionario',
            field=models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.funcionario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcionario',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome Funcionario'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sobrenome'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='telefone',
            field=models.DecimalField(blank=True, decimal_places=11, max_digits=11, null=True, verbose_name='Telefone'),
        ),
    ]
